<a href="https://colab.research.google.com/github/Denhin-ii/Deep-Learning-with-Pytorch/blob/main/DZ_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание N1

## Домашнее задание 0
 Создайте репозиторий на Github. Вся дальнейшая домашка загружается туда. Чуть позже в телеграм чате будет выложена форма для сдачи.


In [289]:
import torch

import numpy as np

## Домашнее задание 1 
реализуйте XOR с помощью 3 нейронов. Запишите ответ в виде выражения, состоящего из объектов neuron() – моделей нейрона с пороговой функцией активации, внутри скобок может быть что угодно. Входы верхнего уровня называются x1 и x2. Пример фрагмента записи: neuron(1x1 + 5x2 - 0.1) + neuron(x1) (ответ будет выглядеть чуть сложнее, но других символов вроде && не потребуется).








И

In [290]:
class Neuron(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.fc = torch.nn.Linear(2, 1)

  def forward(self, x):
    return torch.heaviside(self.fc(x), torch.tensor([0.0]))

In [291]:
neuron = Neuron()
neuron.fc.weight, neuron.fc.bias

(Parameter containing:
 tensor([[ 0.3311, -0.6208]], requires_grad=True), Parameter containing:
 tensor([0.1571], requires_grad=True))

In [292]:
neuron.fc.weight.data = torch.tensor([[0.0, 0.0]])
neuron.fc.bias.data = torch.tensor([0.0])

In [293]:
x = torch.tensor([0.0, 0.0])
neuron(x)

tensor([0.], grad_fn=<NotImplemented>)

!(или)

In [294]:
class Neuron(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.fc = torch.nn.Linear(2, 1)

  def forward(self, y):
    return torch.heaviside(self.fc(y), torch.tensor([1.0]))

In [295]:
neuron = Neuron()
neuron.fc.weight, neuron.fc.bias

(Parameter containing:
 tensor([[-0.6210,  0.0294]], requires_grad=True), Parameter containing:
 tensor([-0.6107], requires_grad=True))

In [296]:
neuron.fc.weight.data = torch.tensor([[0.0, 0.0]])
neuron.fc.bias.data = torch.tensor([1.0])

In [297]:
y = torch.tensor([0.0, 0.0])
neuron(y)

tensor([1.], grad_fn=<NotImplemented>)

или

In [298]:
class Neuron(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.fc = torch.nn.Linear(2, 1)

  def forward(self, y):
    return torch.heaviside(self.fc(c), torch.tensor([1.0]))

In [299]:
neuron = Neuron()
neuron.fc.weight, neuron.fc.bias

(Parameter containing:
 tensor([[ 0.6907, -0.5092]], requires_grad=True), Parameter containing:
 tensor([-0.3984], requires_grad=True))

In [300]:
neuron.fc.weight.data = torch.tensor([[1.0, 1.0]])
neuron.fc.bias.data = torch.tensor([1.0])

In [301]:
c = torch.tensor([1.0, 1.0])
neuron(c)

tensor([1.], grad_fn=<NotImplemented>)

## Домашнее задание 2 
нарисуйте backward граф для выражения a*b+c*d. [Теория и пример оформления.](https://www.youtube.com/watch?v=MswxJw-8PvE) Сравните полученные теоретические значения с аттрибутами grad у исходных тензоров.

In [302]:
a = torch.tensor([2.0], requires_grad=True)
b = torch.tensor([4.0], requires_grad=True)
c = torch.tensor([1.0], requires_grad=True)
d = torch.tensor([5.0], requires_grad=False)

In [303]:
print(a.grad)

None


In [304]:
loss = a*b + c*d
loss.backward()

In [305]:
print(a.grad)

tensor([4.])


## Домашнее задание 3
 Поэксперементируйте с размером тензоров, которые влезут на видеоркарту в Colab. Найдите максимальный размер тензора для типа данных float32, float64, float16, int32, int64. На сколько они отличаются.

In [322]:
torch.rand(size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False)
# для float16
a = None
try:
a = torch.rand(3_800_500_000*2, dtype=torch.float16, device='cuda')
except:
pass
finally:
del a

print(gc.collect())
torch.cuda.empty_cache()
print(torch.cuda.memory_reserved(), torch.cuda.memory_allocated())
print()

IndentationError: ignored

## Домашнее задание 4
Напишите хороший пример неэффективного кода для занятия памяти видеокарты, который вызовет ошибку out of memory

In [316]:
torch.cuda.empty_cache()
name = "a" * 50
del name
gc.collect()

NameError: ignored

## Домашнее задание 5
Используя один линейный слой nn.Linear и один входной тензор x подберите подберите размерности так, чтобы занимать всю видеопамять. Попробуйте применить линейный слой к тензору x. Что произойдет? Кратко опишите ваши эксперименты. Что вы поняли?